### ISSUE TITLE
Scale from centre

### ISSUE THREAD

**Issue by JayParikh20** [androidessence/PinchZoomTextView#9]
is it possible to scale the text is from centre?

**Comment by AdamMc331** [comment]
Hi @JayParikh20! Thanks for the question, it's been a long time since I worked on this. I'm not sure if that was supported originally, but I can look into it this weekend.

**Comment by AdamMc331** [comment]
Since the scaling based on your pinch only changes the text size, it should appear to grow from the center as along as the text itself is centered inside the parent. 

I did this by setting `android:layout_centerHorizontal="true"` inside the layout file. Is this the behavior you were looking for? 


https://drive.google.com/file/d/1axYr7Cskd1nw7l97eDUZnfFzQkqTFKBe/view?usp=sharing

**Comment by AdamMc331** [comment]
Additionally, using `android:gravity="center"` will keep the text centered as it scales up, too.

**Comment by JayParikh20** [comment]
Yes, i was looking for something similar. Thanks for your help!

**Comment by AdamMc331** [comment]
Great! Thanks for nudging this old library though. I'm gonna freshen up these dependencies, get rid of the Java modules, and release it with a 2020 feel. 😆 So keep an eye out for that.
